# Generated by Django 4.2.20 on 2025-03-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='account',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
